#!/usr/bin/env node
initEnv() // Setup the test env variables before we require the server

const server = require('app/server')
const fs = require('fs')
const path = require('path')
const apiClient = require('./api_client')

const BASE_URL = `http://localhost:${process.env.PORT}/v1`

function initEnv () {
  const TEST_ENV = {
    NODE_ENV: 'test',
    PORT: 3006
  }
  Object.assign(process.env, TEST_ENV)
}

function suites () {
  const suitesPath = path.join(__dirname, '/suites')
  const allSuites = fs.readdirSync(suitesPath).map(filename => path.parse(filename).name)
  const customSuites = process.env.SUITES && process.env.SUITES.split(',')
  return customSuites || allSuites
}

function suiteHeader (suiteName) {
  console.log('\n##################################################')
  console.log(`# Suite: ${suiteName}`)
  console.log('##################################################')
}

async function run () {
  const client = apiClient({BASE_URL})
  await server.start()
  for (let suiteName of suites()) {
    suiteHeader(suiteName)
    const suite = require(`./suites/${suiteName}`)
    await suite(client)
  }
  process.exit(0)
}

run()
