#!/usr/bin/env bash

set -ex

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $SCRIPT_DIR
export PATH=.:$PATH

source setup

npm start &
SERVER_PID=$!
trap "kill -SIGINT $SERVER_PID" EXIT

wait-for-server $BASE_URL

for suite in $(ls suites); do
  export SUITE=$suite
  export LOG_DIR=$BASE_LOG_DIR/$SUITE
  mkdir -p $LOG_DIR
  source suites/$SUITE
done
