#!/usr/bin/env node

function uuid() {
  const time = (new Date()).valueOf().toString()
  const random = Math.random().toString()
  return require('crypto').createHash('sha1').update(time + random).digest('hex')
}

console.log(uuid())
