#!/usr/bin/env node

const http = require('http')

const url = process.argv[2]

function tryGet () {
  http.get(url).on('error', error => {
    console.log('wait for server...')
    if (error.errno === 'ECONNREFUSED') setTimeout(tryGet, 100)
  })
}

tryGet()
